using System;
using System.Collections.Generic;

namespace GrantCountyAs400.PersistenceAdapter.Models
{
    public partial class AcctEmployee
    {
        public decimal? Group { get; set; }
        public decimal? Year { get; set; }
        public string Budget { get; set; }
        public string Name { get; set; }
        public decimal Number { get; set; }
        public decimal? Ssnumber { get; set; }
        public decimal? Count { get; set; }
        public DateTime? LastHistory { get; set; }
        public decimal? Fund { get; set; }
        public decimal? Department { get; set; }
        public decimal? RetirementNumber { get; set; }
        public decimal? RetirementFlag { get; set; }
        public decimal? RetirementLock { get; set; }
        public decimal? RetirementCode { get; set; }
        public string RetirementOption { get; set; }
        public DateTime? Emretseldate { get; set; }
        public string Emretselcode { get; set; }
        public string Emretipmgr { get; set; }
        public string PayCode { get; set; }
        public decimal? PayStatus { get; set; }
        public DateTime? HireDate { get; set; }
        public DateTime? ServiceDate { get; set; }
        public decimal? ServiceYears { get; set; }
        public DateTime? AnniversaryDate { get; set; }
        public DateTime? ReviewDate { get; set; }
        public DateTime? Date1 { get; set; }
        public DateTime? Date2 { get; set; }
        public DateTime? TerminationDate { get; set; }
        public string TerminationType { get; set; }
        public string PositionCode { get; set; }
        public string Branch { get; set; }
        public string Emadaccnt { get; set; }
        public decimal? BondType { get; set; }
        public decimal? BondPurchased { get; set; }
        public decimal? BondCurrent { get; set; }
        public decimal? Embondcnt { get; set; }
        public decimal? Emupdtlast { get; set; }
        public decimal? Emupdtcnt { get; set; }
        public decimal? Emupdtflag { get; set; }
        public decimal? Rate { get; set; }
        public decimal? OldRate { get; set; }
        public decimal? EmpWarrantNumber { get; set; }
        public string Emsftabl { get; set; }
        public decimal? EmpSaif { get; set; }
        public decimal? EmpFilled { get; set; }
        public decimal? EmpPercent { get; set; }
        public decimal? EmpLongevity { get; set; }
        public decimal? EmpLongevityAmount { get; set; }
        public decimal? EmpFicaExempt { get; set; }
        public decimal? EmpFicaCode { get; set; }
        public decimal? Emhldytakn { get; set; }
        public string EmpEeofunction { get; set; }
        public string JobCode { get; set; }
        public string Table { get; set; }
        public string Grade { get; set; }
        public string Step { get; set; }
        public string BargainingUnit { get; set; }
        public string MeritStatus { get; set; }
        public decimal? Type { get; set; }
        public decimal? Weeks { get; set; }
        public decimal? Emweeksqtd { get; set; }
        public string Flsa { get; set; }
        public decimal? CurrentGross { get; set; }
        public decimal? CurrentTax { get; set; }
        public decimal? Emcdeds { get; set; }
        public decimal? Emcdefd { get; set; }
        public decimal? CurrentNonTaxable { get; set; }
        public decimal? CurrentTaxable { get; set; }
        public decimal? CurrentFederalWithholding { get; set; }
        public decimal? CurrentStateWithholding { get; set; }
        public decimal? CurrentFica { get; set; }
        public decimal? CurrentFicaBenefit { get; set; }
        public decimal? CurrentNetPay { get; set; }
        public decimal? CurrentFicaGross { get; set; }
        public decimal? CurrentMedicalGross { get; set; }
        public decimal? CurrentMedical { get; set; }
        public decimal? CurrentMedicalBenefit { get; set; }
        public decimal? CurrentTaxableBenefit { get; set; }
        public decimal? CurrentRetirementGross { get; set; }
        public decimal? CurrentRetirement { get; set; }
        public decimal? CurrentRetirementBenefit { get; set; }
        public decimal? Emcretemp { get; set; }
        public decimal? Emchrsreg { get; set; }
        public decimal? Emcamtreg { get; set; }
        public decimal? QtrlyGross { get; set; }
        public decimal? QtrlyDeferredGross { get; set; }
        public decimal? QtrlyNonTaxable { get; set; }
        public decimal? QtrlyTaxable { get; set; }
        public decimal? QtrlyFicaGross { get; set; }
        public decimal? QtrlyFederalWihholding { get; set; }
        public decimal? QtrlyStateWithholding { get; set; }
        public decimal? QtrlyFica { get; set; }
        public decimal? QtrlyFicaBenefit { get; set; }
        public decimal? QtrlyMedicalGross { get; set; }
        public decimal? QtrlyMedical { get; set; }
        public decimal? QtrlyMedicalBenefit { get; set; }
        public decimal? QtrlyTaxableBenefit { get; set; }
        public decimal? QtrlyNetPay { get; set; }
        public decimal? QtrlyRetirementGross { get; set; }
        public decimal? QtrlyRetirement { get; set; }
        public decimal? QtrlyRetirementBenefit { get; set; }
        public decimal? QtrltRetirementBenefitEmployer { get; set; }
        public decimal? YearlyGross { get; set; }
        public decimal? YearlyDeferredGross { get; set; }
        public decimal? YearlyNontaxable { get; set; }
        public decimal? YearlyTaxable { get; set; }
        public decimal? YearlyFicaGross { get; set; }
        public decimal? YearlyFederalWithholding { get; set; }
        public decimal? YearlyStateWithholding { get; set; }
        public decimal? YearlyFica { get; set; }
        public decimal? YearlyFicaBenefit { get; set; }
        public decimal? YearlyMedicalGross { get; set; }
        public decimal? YearlyMedical { get; set; }
        public decimal? YearlyMedicalBenefit { get; set; }
        public decimal? YearlyTaxableBenefit { get; set; }
        public decimal? YearlyNetPay { get; set; }
        public decimal? YearlyTotalPay { get; set; }
        public decimal? YearlyRetirementGross { get; set; }
        public decimal? YearlyRetirement { get; set; }
        public decimal? YearlyRetirementBenefit { get; set; }
        public decimal? YearlyRetirementBenefitEmployer { get; set; }
        public int Id { get; set; }
    }
}
